In [2]:
import numpy as np
data=np.loadtxt("F:\\ML and DataScience Coding Ninjas\\Machine Learning\\2. Linear Regression\\Diabetes\\diabetes_train.csv",delimiter=",")
data

array([[-4.91050164e-02, -4.46416365e-02,  1.60854917e-01, ...,
         2.80165065e-02,  1.13486232e-02,  3.46000000e+02],
       [-7.09002471e-02,  5.06801187e-02, -8.91974838e-02, ...,
        -1.29079423e-02, -5.49250874e-02,  1.04000000e+02],
       [ 1.75052192e-03, -4.46416365e-02, -7.08746786e-02, ...,
        -2.25121719e-02,  7.20651633e-03,  4.90000000e+01],
       ...,
       [ 2.35457526e-02, -4.46416365e-02,  7.03187031e-02, ...,
        -1.91970476e-02, -9.36191133e-03,  2.88000000e+02],
       [ 1.62806757e-02,  5.06801187e-02,  7.24743273e-02, ...,
        -2.36445576e-02,  6.10539062e-02,  1.31000000e+02],
       [-9.14709343e-03,  5.06801187e-02, -3.09956318e-02, ...,
         6.20931562e-03,  2.79170509e-02,  4.20000000e+01]])

In [10]:
X_train=data[:,:10]
Y_train=data[:,10]

In [11]:
# from sklearn import model_selection
# X_train,X_test,Y_train,Y_test=model_selection.train_test_split(x,y)
from sklearn.linear_model import LinearRegression
alg1=LinearRegression()
alg1.fit(X_train,Y_train)

LinearRegression()

In [12]:
alg1.coef_, alg1.intercept_

(array([  21.73408096, -256.66866675,  569.60940087,  303.63233545,
        -833.11088526,  525.74313633,  136.07129167,  140.89458927,
         731.44498492,   53.32119133]), 150.702574894566)

In [13]:
alg1.predict(X_train)

array([271.80601321,  67.74312487,  97.62639376, 217.73083979,
       161.85116331,  76.61540802, 185.8637718 , 169.48651056,
        50.32993631, 221.73035041, 104.78354162,  88.82353998,
       128.4222385 ,  67.83023141, 148.12781445, 140.9107449 ,
        73.85102659, 101.60798054, 196.27596561, 111.9026676 ,
       128.84447347, 160.65837273,  92.80849254,  88.83037153,
        74.09816075, 151.73148128, 195.82104885, 120.19772331,
       241.40935754, 144.99479251,  60.29763285, 175.63746048,
       105.99537819, 111.80918785, 164.57390052, 225.49344075,
       176.72703646,  90.31871435, 170.13070006, 201.84237238,
       158.84496158, 140.18416701,  37.66168052, 108.10411103,
       122.66391547, 212.38495926, 242.11931864, 147.26273619,
       172.34620392,  80.08103175, 149.15252383,  84.63423717,
       204.02033971, 155.52419191, 159.30657722, 132.64193668,
       174.45425169, 157.42040586, 218.8386151 , 116.90051683,
       132.75768073, 160.87879425,  68.35303454, 233.09

In [8]:
testing_data=np.loadtxt("F:\\ML and DataScience Coding Ninjas\\Machine Learning\\2. Linear Regression\\Diabetes\\diabetes_test.csv",delimiter=",")
testing_data

array([[ 0.02354575,  0.05068012, -0.0374625 , ..., -0.03949338,
        -0.03075121, -0.01350402],
       [-0.07816532, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.01811827, -0.08391984],
       [-0.03094232,  0.05068012,  0.00133873, ...,  0.1081111 ,
         0.08379677,  0.00306441],
       ...,
       [ 0.0090156 , -0.04464164, -0.01267283, ...,  0.03430886,
         0.02337484, -0.0052198 ],
       [ 0.01991321, -0.04464164, -0.03422907, ...,  0.03283281,
         0.02472532,  0.06933812],
       [ 0.01628068,  0.05068012,  0.00996123, ..., -0.03949338,
         0.01703713,  0.00720652]])

In [18]:
ans=alg1.predict(testing_data)
np.savetxt('predicted_data.csv', ans, delimiter=',', fmt='%.5f')